from scenes._shared.design import *
class Film(Stage):
    def construct(self):
        water_y=1.3;H=1.7;W=1.6;rho=ValueTracker(.6);cy=ValueTracker(water_y+H/2-H*.6)
        water=Rectangle(width=6.2,height=4.2,fill_color=self.palette['primary'],fill_opacity=.13,stroke_opacity=0).move_to([0,water_y-2.1,0]);surface=self.line([-3.1,water_y,0],[3.1,water_y,0],'primary',2)
        def body(color='secondary'):return Rectangle(width=W,height=H,fill_color=self.palette[color],fill_opacity=.85 if color=='secondary' else .4,stroke_color=self.palette['ink'],stroke_width=2.5).move_to([0,cy.get_value(),0])
        block=always_redraw(body)
        self.at('A piece of wood');self.add(water,block,surface)
        self.at('The water is quietly');support=Arrow([0,-1.0,0],[0,-.1,0],buff=0,color=self.palette['primary'],stroke_width=4);weight=Arrow([0,3.4,0],[0,2.5,0],buff=0,color=self.palette['secondary'],stroke_width=4);self.play(GrowArrow(support),GrowArrow(weight),run_time=.6)
        self.at('Imagine holding');self.play(FadeOut(support),FadeOut(weight),cy.animate.set_value(-.15),run_time=1.5)
        self.at('Water pressure increases');top=cy.get_value()+H/2;bottom=cy.get_value()-H/2
        up_len=.48*(water_y-bottom);down_len=.48*(water_y-top)
        ups=VGroup(*[Arrow([x,bottom-up_len,0],[x,bottom,0],buff=0,color=self.palette['primary'],stroke_width=3) for x in [-.5,0,.5]])
        downs=VGroup(*[Arrow([x,top+down_len,0],[x,top,0],buff=0,color=self.palette['primary'],stroke_width=3) for x in [-.5,0,.5]])
        self.play(FadeIn(ups),FadeIn(downs),run_time=.5)
        self.at('The bottom feels');self.focus_outline(ups,run_time=.6)
        self.at('The sideways pushes');sides=VGroup(*[Arrow([sign*(W/2+.4),y,0],[sign*W/2,y,0],buff=0,color=self.palette['muted'],stroke_width=2.5) for y in [-.6,.3] for sign in [-1,1]]);self.play(FadeIn(sides),run_time=.5)
        self.at('What remains');self.play(FadeOut(sides),run_time=.4)
        self.at('Now imagine replacing');self.play(FadeOut(block),run_time=.4);parcel=body('primary');self.play(FadeIn(parcel),run_time=.5)
        self.at('The surrounding water');self.focus_outline(parcel,run_time=.6)
        self.at('That little parcel');self.play(FadeOut(ups),FadeOut(downs),run_time=.4);up=Arrow([-1.65,-1.4,0],[-1.65,.1,0],buff=0,color=self.palette['primary']);down=Arrow([1.65,1.1,0],[1.65,-.4,0],buff=0,color=self.palette['secondary']);self.play(GrowArrow(up),GrowArrow(down),run_time=.7)
        self.at('So the upward support');note=self.label('support = parcel weight',[0,-2.3,0],'ink','label');self.play(FadeIn(note),run_time=.5)
        self.at('Put the block back');self.play(FadeOut(parcel),FadeOut(up),FadeOut(down),run_time=.5);block=always_redraw(body);self.add(block)
        self.at('A floating block settles');self.play(cy.animate.set_value(water_y+H/2-H*.6),FadeOut(note),run_time=1.5)
        self.at('For this uniform wood');ratio=self.label('density: 60% of water',[0,-1.8,0],'ink','label');self.play(FadeIn(ratio),run_time=.5)
        def submerged():
         height=H*rho.get_value()
         return Rectangle(width=W,height=height,fill_color=self.palette['primary'],fill_opacity=.3,stroke_color=self.palette['primary'],stroke_width=3).move_to([0,water_y-height/2,0])
        sub=always_redraw(submerged)
        self.at('Sixty percent of its volume');self.add(sub);label=self.label('60% submerged',[0,-2.45,0],'primary','label');self.play(FadeIn(label),run_time=.5)
        self.at('A denser block');self.play(FadeOut(ratio),FadeOut(label),rho.animate.set_value(.8),cy.animate.set_value(water_y+H/2-H*.8),run_time=1.5)
        self.at('At eighty percent');ratio=self.replace_label(None,self.label('density: 80% of water',[0,-1.8,0],'ink','label'));label=self.replace_label(None,self.label('80% submerged',[0,-2.45,0],'primary','label'))
        self.at('We are ignoring');self.play(FadeOut(ratio),FadeOut(label),run_time=.5)
        self.at('Floating is a quiet');self.finish()
