from scenes._shared.design import *
class Film(Stage):
    def construct(self):
        INK=self.palette['ink'];PAPER=self.palette['background'];mu=.2;cy=2.1
        # Horizontal wooden cylinder, with rear rope segments occluded by its body.
        def assembly(n):
            g=VGroup();back=VGroup();front=VGroup();ts=np.linspace(PI,PI+TAU*n,401)
            def pt(t):return np.array([-1.2+2.4*(t-PI)/(TAU*n)+.25*np.sin(t),cy+.8*np.cos(t),0])
            for a,b in zip(ts[:-1],ts[1:]):
                line=Line(pt(a),pt(b),color='#C4A676',stroke_width=5);(front if np.sin((a+b)/2)>=0 else back).add(line)
            body=Rectangle(width=2.4,height=1.6,fill_color='#A98760',fill_opacity=1,stroke_width=0).move_to([0,cy,0]);ends=VGroup(Ellipse(width=.5,height=1.6,fill_color='#C6A87F',fill_opacity=1,stroke_color='#92754F',stroke_width=2).move_to([x,cy,0]) for x in [-1.2,1.2]);grain=VGroup(Line([-1.1,cy+y,0],[1.1,cy+y+.03,0],color='#98784F',stroke_width=1.5) for y in [-.5,-.15,.3,.55]);leads=VGroup(Line([-1.2,cy-.8,0],[-1.2,cy-1.7,0],color='#C4A676',stroke_width=5),Line([1.2,cy-.8,0],[1.2,cy-1.8,0],color='#C4A676',stroke_width=5));pot=VGroup(ArcBetweenPoints([-1.6,cy-1.7,0],[-.8,cy-1.7,0],angle=PI/2,color='#9B7866',stroke_width=3),RoundedRectangle(width=.8,height=.65,corner_radius=.16,fill_color='#B9947B',fill_opacity=1,stroke_color='#8D6E5E',stroke_width=2).move_to([-1.2,cy-2,0]));hold=Circle(radius=.13,color=INK,stroke_width=3).move_to([1.2,cy-1.8,0]);return VGroup(back,body,grain,ends,front,leads,pot,hold).scale(1.2,about_point=np.array([0,1.3,0]))
        subject=assembly(1);self.add(subject);self.at('A rope');self.at('The post contributes');self.at('Imagine the rope');threshold=self.label('just before slipping',[0,4.3,0],'ink','label');self.play(FadeIn(threshold),run_time=.7);self.at('We compare');labels=VGroup(self.label('load',[-1.8,-.65,0],'ink','label'),self.label('hold',[1.8,-.65,0],'ink','label'));self.play(FadeIn(labels),run_time=.6);self.at('More wrap');second=assembly(2);self.play(ReplacementTransform(subject,second),run_time=1.2);subject=second;self.at('Here is the total');self.play(FadeOut(subject),FadeOut(labels),run_time=.7)
        x0=-2.7;y0=-1.6
        axis=VGroup(Arrow([x0,y0,0],[2.9,y0,0],buff=0,color=INK,stroke_width=2),Arrow([x0,y0,0],[x0,2.9,0],buff=0,color=INK,stroke_width=2));lab=VGroup(self.label('wrap angle in radians',[0,-2.25,0],'ink','label'),self.label('maximum load / hold',[0,3.45,0],'ink','label'))
        def xy(t):return np.array([x0+5.1*t/(4*PI),y0+4*np.exp(mu*t)/np.exp(mu*4*PI),0])
        curve=ParametricFunction(xy,t_range=[0,4*PI],color=self.palette['primary'],stroke_width=4);self.play(Create(axis),FadeIn(lab),run_time=.6);self.at('At the slipping');self.play(Create(curve),run_time=2);self.at('This happens');self.at('For one illustrative');p1=xy(TAU);dot1=Dot(p1,color=self.palette['primary']);tag1=self.label('1 turn: 3.5',[.3,p1[1]-.6,0],'ink','label').scale(.9);mu_label=self.label('illustration: μ = 0.2',[0,-3.1,0],'ink','label').scale(.8);self.play(FadeIn(dot1),FadeIn(tag1),FadeIn(mu_label),run_time=.7);self.at('Two turns');p2=xy(2*TAU);dot2=Dot(p2,color=self.palette['primary']);tag2=self.label('2 turns: 12.3',[1,2.9,0],'ink','label').scale(.9);self.play(FadeIn(dot2),FadeIn(tag2),run_time=.7);self.at('The ideal capstan');eq=self.label('maximum ratio = exp(μ × wrap angle)',[0,-3.8,0],'ink','label').scale(.85);self.play(FadeIn(eq),run_time=.6);self.at('Below the slipping');self.play(FadeOut(VGroup(axis,lab,curve,dot1,tag1,dot2,tag2,mu_label,eq,threshold)),run_time=.8);subject=assembly(2);self.play(FadeIn(subject),run_time=.8);self.at('Real rope');self.at('This is a model');self.at('A gentle curve');self.finish()
