from scenes._shared.design import *
class Film(Stage):
    def construct(self):
        c=np.array([0,1.25,0]);a=2.6;b=1.9;f=math.sqrt(a*a-b*b);F=c+LEFT*f;G=c+RIGHT*f
        outline=Ellipse(width=2*a,height=2*b,color=self.palette['ink'],stroke_width=3).move_to(c)
        marks=VGroup(Dot(F,radius=.085,color=self.palette['primary']),Dot(G,radius=.085,color=self.palette['secondary']))
        self.add(outline,marks)
        angle=ValueTracker(.85)
        def point():return c+np.array([a*math.cos(angle.get_value()),b*math.sin(angle.get_value()),0])
        path=always_redraw(lambda:VGroup(self.line(F,point(),'primary',4),self.line(point(),G,'secondary',4)))
        self.play(Create(path),run_time=1.5)
        self.at('Change its direction');self.play(angle.animate.set_value(2.15),run_time=2.4);self.play(angle.animate.set_value(.85),run_time=2.4)
        self.at('Those two points');fl=self.label('foci',[0,.65,0],'ink','detail');self.play(FadeIn(fl),run_time=.6)
        self.at('Every point on');total=self.label('one fixed total',[0,-1.6,0],'ink','label');self.play(FadeIn(total),run_time=.5);self.play(angle.animate.set_value(1.55),run_time=2)
        self.at('A loop of string');self.play(angle.animate.set_value(.85),run_time=1.6)
        self.at('Now pause at');P=point().copy();path.clear_updaters();self.play(FadeOut(fl),run_time=.4)
        incoming=(P-F)/np.linalg.norm(P-F);H=P+incoming*np.linalg.norm(P-G)
        normal=(H-G)/np.linalg.norm(H-G);tangent=np.array([-normal[1],normal[0],0])
        self.at('Continue the first');extension=self.line(P,H,'secondary',4);ghost=Dot(H,radius=.07,color=self.palette['secondary']);self.play(Create(extension),FadeIn(ghost),run_time=1.2)
        self.at('Give this new segment');self.focus_outline(VGroup(extension,path[1]),run_time=1)
        self.at('The total length');self.play(path[1].animate.set_opacity(.2),run_time=.5)
        self.at('Draw the perpendicular');mid=(G+H)/2;connector=DashedLine(G,H,dash_length=.1,color=self.palette['muted'],stroke_width=2);mirror=self.line(P-tangent*1.45,P+tangent*1.55,'ink',3);corner=RightAngle(Line(mid,mid+tangent),Line(mid,mid+normal),length=.16,color=self.palette['muted']);self.play(Create(connector),Create(mirror),Create(corner),run_time=1.4)
        self.at('This line is');label=self.label('candidate mirror',[-1.3,4.2,0],'ink','detail');self.play(FadeIn(label),run_time=.5)
        self.at('The two equal segments');arc1=Angle(Line(P,P+tangent),Line(P,F),radius=.32,color=self.palette['primary']);arc2=Angle(Line(P,G),Line(P,P-tangent),radius=.32,color=self.palette['secondary']);self.play(Create(arc1),Create(arc2),path[1].animate.set_opacity(1),run_time=.8)
        self.at('Why does this mirror');self.play(FadeOut(arc1),FadeOut(arc2),FadeOut(corner),run_time=.5)
        self.at('Move to another');Q=P+tangent*.7;q=Dot(Q,radius=.075,color=self.palette['accent']);trial=VGroup(self.line(F,Q,'primary',3),self.line(Q,G,'secondary',3));self.play(path.animate.set_opacity(.22),FadeIn(q),Create(trial),run_time=1.1)
        self.at('The distance to the focus');copyline=self.line(Q,H,'secondary',3);self.play(Create(copyline),run_time=.8)
        self.at('So unfold that');self.play(trial[1].animate.set_opacity(.15),run_time=.7)
        self.at('It now bends');self.focus_outline(q,run_time=.8)
        self.at('A bent route');comparison=self.label('bent path > straight path',[0,-2.25,0],'ink','label');self.play(FadeIn(comparison),run_time=.7)
        self.at('That point must');self.focus_outline(q,run_time=.8)
        self.at('Only the original');self.play(FadeOut(q),FadeOut(trial),FadeOut(copyline),path.animate.set_opacity(1),run_time=.9)
        self.at('The candidate mirror is');self.play(FadeOut(label),FadeOut(comparison),FadeOut(total),FadeOut(connector),FadeOut(extension),FadeOut(ghost),run_time=.8);tlabel=self.label('tangent · equal angles',[0,-1.7,0],'ink','label');self.play(FadeIn(tlabel),run_time=.5)
        self.at('Equal angles explain');traveler=Dot(F,radius=.07,color=self.palette['accent']);self.add(traveler);route=VMobject().set_points_as_corners([F,P,G]);self.play(MoveAlongPath(traveler,route,rate_func=linear),run_time=2.4);self.remove(traveler)
        self.at('This is an ideal');self.play(FadeOut(mirror),FadeOut(tlabel),FadeOut(path),run_time=.6)
        self.at('Yet this quiet');rays=VGroup(*[VGroup(self.line(F,c+np.array([a*math.cos(t),b*math.sin(t),0]),'primary',1.7),self.line(c+np.array([a*math.cos(t),b*math.sin(t),0]),G,'secondary',1.7)).set_opacity(.4) for t in np.linspace(.2,TAU-.2,19)]);self.play(LaggedStart(*[Create(r) for r in rays],lag_ratio=.07),run_time=4);self.finish()
