from scenes._shared.design import *
class Film(Stage):
    def construct(self):
        lat=35*DEGREES;lon=65*DEGREES
        def xyz(phi,lam):return np.array([math.cos(phi)*math.sin(lam),math.sin(phi),math.cos(phi)*math.cos(lam)])
        A=xyz(lat,-lon);B=xyz(lat,lon);theta=math.acos(np.dot(A,B));u=np.linspace(0,1,121)
        great=np.array([(math.sin((1-t)*theta)*A+math.sin(t*theta)*B)/math.sin(theta) for t in u]);parallel=np.array([xyz(lat,-lon+2*lon*t) for t in u])
        def mapped(points):return np.array([[math.atan2(p[0],p[2])*2.4,(math.asin(p[1])-lat)*2.4+1,0] for p in points])
        def linepath(points,col,width=5):return VMobject().set_points_as_corners(points).set_stroke(self.palette[col],width=width)
        mapgreat=mapped(great);mapparallel=mapped(parallel);frame=Rectangle(width=6.4,height=3.3,stroke_color=self.palette['muted'],stroke_width=2).move_to([0,1.8,0]);self.add(frame)
        for y in [1,2,3]:self.add(self.line([-3.2,y,0],[3.2,y,0],'surface',2))
        straight=linepath(mapparallel,'secondary');arc=linepath(mapgreat,'primary');marks=VGroup(*[Dot(p,radius=.11,color=self.palette['ink']) for p in [mapgreat[0],mapgreat[-1]]]);self.add(straight,marks);self.play(Create(arc),run_time=2);self.say('A curved line. A shorter route.')
        self.at('Let us keep the same');self.play(*[FadeOut(m) for m in list(self.mobjects) if m not in [self.caption,straight,arc,marks]],run_time=.5)
        center=np.array([0,1.2,0]);r=2.5;tilt=20*DEGREES;basis=np.array([[1,0,0],[0,math.cos(tilt),-math.sin(tilt)],[0,math.sin(tilt),math.cos(tilt)]])
        project=lambda points:np.array([center+r*np.r_[(basis@p)[:2],0] for p in points]);sphere=Circle(radius=r,fill_color=self.palette['primary'],fill_opacity=.045,stroke_color=self.palette['ink'],stroke_width=3).move_to(center);self.add(sphere)
        mesh=VGroup()
        for latitude in [-60,-30,0,30,60]:mesh.add(linepath(project([xyz(latitude*DEGREES,a) for a in np.linspace(-PI,PI,181)]),'muted',1).set_stroke(opacity=.2))
        for longitude in [-60,-30,0,30,60]:mesh.add(linepath(project([xyz(a,longitude*DEGREES) for a in np.linspace(-PI/2,PI/2,121)]),'muted',1).set_stroke(opacity=.2))
        self.add(mesh)
        self.play(Transform(straight,linepath(project(parallel),'secondary')),Transform(arc,linepath(project(great),'primary')),*[m.animate.move_to(p) for m,p in zip(marks,project([A,B]))],run_time=2)
        self.at('The horizontal map line');self.say('Latitude circle');equator=linepath(project([xyz(0,a) for a in np.linspace(-PI,PI,181)]),'muted',2);self.add(equator)
        self.at('Now take the plane');W=(B-math.cos(theta)*A)/math.sin(theta);whole=linepath(project([math.cos(a)*A+math.sin(a)*W for a in np.linspace(0,TAU,181)]),'primary',2).set_stroke(opacity=.35);self.add(whole);radii=VGroup(*[self.line(center,p,'muted',3) for p in project([A,B])]);self.play(Create(radii),run_time=1);self.add(Dot(center,radius=.065,color=self.palette['ink']),self.label('center',center+DOWN*.35,'ink','detail'));self.say('A plane through the center')
        self.at('The shorter arc');self.play(Indicate(arc),run_time=1)
        self.at('Notice that it curves');self.say('The map changes the picture.')
        self.at('In our example');self.add(self.label('35° N • 130° longitude apart',[0,-2,0],'ink','detail'))
        self.at('following the latitude takes');self.add(self.label('latitude: 1.86 r',[0,-2.7,0],'secondary','label'))
        self.at('The great circle takes');self.add(self.label('great circle: 1.67 r',[0,-3.3,0],'primary','label'))
        self.at('A useful way to picture');self.play(*[FadeOut(m) for m in list(self.mobjects) if m is not self.caption and m is not sphere and m is not arc and m is not marks],run_time=.7);self.say('Turn the starting point north.')
        pole=center+UP*r;dest=center+r*np.array([math.sin(theta),math.cos(theta),0]);meridian=Arc(radius=r,start_angle=PI/2,angle=-theta,arc_center=center,stroke_color=self.palette['primary'],stroke_width=7);target_basis=np.array([W,A,np.cross(W,A)]);delta=target_basis@basis.T;angle=math.acos(np.clip((np.trace(delta)-1)/2,-1,1));axis=np.array([delta[2,1]-delta[1,2],delta[0,2]-delta[2,0],delta[1,0]-delta[0,1]])/(2*math.sin(angle));x,y,z=axis;K=np.array([[0,-z,y],[z,0,-x],[-y,x,0]])
        def rotate_view(m,alpha):
            q=angle*alpha;rotation=np.eye(3)+math.sin(q)*K+(1-math.cos(q))*(K@K)
            points=np.array([center+r*np.r_[(rotation@basis@p)[:2],0] for p in great]);arc.set_points_as_corners(points);marks[0].move_to(points[0]);marks[1].move_to(points[-1])
        self.play(UpdateFromAlphaFunc(arc,rotate_view),run_time=2);arc.set_stroke(width=8);sphere.set_stroke(opacity=.4)
        self.at('Any sideways motion');self.say('Sideways motion adds distance.');self.add(self.label('required polar angle: θ',[0,-2,0],'ink','detail'),self.line(center,pole,'muted',2),self.line(center,dest,'muted',2),Arc(radius=.65,start_angle=PI/2,angle=-theta,arc_center=center,stroke_color=self.palette['ink'],stroke_width=2),self.label('θ',center+[.6,.6,0],'ink','detail'))
        self.at('This explanation assumes');self.say('A sphere. A surface route.')
        self.at('Real flight planning');self.say('Real journeys add constraints.')
        self.at('A line that looks');self.say('Let the world explain the map.');self.finish()
