from scenes._shared.design import *
class Film(Stage):
    def construct(self):
        temp=ValueTracker(80);c=np.array([-1.1,2.2,0])
        body=RoundedRectangle(width=2.2,height=1.6,corner_radius=.25,stroke_color=self.palette['ink'],stroke_width=3,fill_color=self.palette['background'],fill_opacity=1).move_to(c)
        handle=Arc(radius=.48,start_angle=-PI/2,angle=PI,stroke_color=self.palette['ink'],stroke_width=5).move_to(c+[1.18,0,0]);saucer=Ellipse(width=3,height=.3,stroke_color=self.palette['muted']).move_to(c+[0,-.95,0])
        liquid=Ellipse(width=2.08,height=.35,fill_color=self.palette['accent'],fill_opacity=.65,stroke_color=self.palette['ink']).move_to(c+[0,.57,0])
        self.add(saucer,handle,body,liquid)
        x=2.;y0=.3;scale=.045
        rail=self.line([x,y0,0],[x,y0+80*scale,0],'muted',2)
        room=self.line([x-.25,y0+20*scale,0],[x+.25,y0+20*scale,0],'primary',3)
        bar=always_redraw(lambda:Line([x,y0+20*scale,0],[x,y0+temp.get_value()*scale,0],stroke_color=self.palette['secondary'],stroke_width=12))
        readout=always_redraw(lambda:self.label(f'{temp.get_value():.1f}°',[x-.1,y0+temp.get_value()*scale+.45,0],'ink','label'))
        self.add(rail,room,bar,readout);self.at('A warm cup');self.play(temp.animate.set_value(50),run_time=4,rate_func=lambda t:2*(1-2**(-t)))
        self.at('As that temperature');self.play(temp.animate.set_value(35),run_time=2)
        self.at('Imagine a room');temp.set_value(80);roomlabel=self.label('room 20°',[.95,.9,0],'primary','label');self.play(FadeIn(roomlabel),run_time=.4)
        self.at('The gap is sixty');gap=self.label('gap 60°',[0,-.2,0],'secondary','claim');self.play(FadeIn(gap),run_time=.4)
        self.at('In this simple');note=self.label('equal time → half the gap',[0,-1.1,0],'ink','label');self.play(FadeIn(note),run_time=.5)
        self.at('Sixty becomes');self.play(temp.animate.set_value(50),FadeOut(gap),run_time=1);gap=self.label('gap 30°',[0,-.2,0],'secondary','claim');self.add(gap);self.play(temp.animate.set_value(35),FadeOut(gap),run_time=1);gap=self.label('gap 15°',[0,-.2,0],'secondary','claim');self.add(gap);self.play(temp.animate.set_value(27.5),FadeOut(gap),run_time=1);gap=self.label('gap 7.5°',[0,-.2,0],'secondary','claim');self.add(gap)
        self.at('Notice what');self.focus_outline(bar,run_time=.7)
        self.at('It is the distance');self.focus_outline(room,run_time=.7)
        self.at('The tea goes');self.play(FadeOut(gap),FadeOut(note),run_time=.4);sequence=self.label('80° → 50° → 35°',[0,-.6,0],'ink','claim');self.play(FadeIn(sequence),run_time=.5)
        self.at('Twenty degrees stays');baseline=self.label('20 + 60    20 + 30    20 + 15',[0,-1.45,0],'primary','label');baseline.scale(.85);self.play(FadeIn(baseline),run_time=.5)
        self.at('Connect those');self.play(FadeOut(sequence),FadeOut(baseline),run_time=.4)
        # Keep the original cup while the same temperature readout maps to a graph.
        axes=Axes(x_range=[0,4,1],y_range=[20,80,20],x_length=4.5,y_length=2.4,axis_config={'include_tip':False,'color':self.palette['muted']}).move_to([0,-.7,0]);curve=axes.plot(lambda t:20+60*2**(-t),x_range=[0,4],color=self.palette['secondary']);self.play(Create(axes),run_time=.6);t=ValueTracker(0);dot=always_redraw(lambda:Dot(axes.c2p(t.get_value(),20+60*2**(-t.get_value())),radius=.07,color=self.palette['secondary']));self.add(dot);temp.add_updater(lambda m:m.set_value(20+60*2**(-t.get_value())));self.play(Create(curve),t.animate.set_value(4),run_time=1.7,rate_func=linear)
        label=self.label('equal time steps',[0,-2.4,0],'muted','label');self.add(label)
        self.at('A large gap');self.focus_outline(curve,run_time=.5)
        self.at('A small gap');self.play(t.animate.set_value(3),run_time=.6)
        self.at('This is exponential');rule=self.label('gap = 60 × ½ᵗ',[0,-3.05,0],'ink','label');self.play(FadeIn(rule),run_time=.5)
        self.at('The halving time');self.play(FadeOut(rule),run_time=.4)
        self.at('Real tea');self.wait(.2)
        self.at('This model assumes');assumption=self.label('steady room • constant factor',[0,-3.05,0],'muted','label');assumption.scale(.8);self.play(FadeIn(assumption),run_time=.4)
        self.at('Even a cooling');self.finish()
