from scenes._shared.design import *
class Film(Stage):
    def construct(self):
        INK=self.palette['ink'];TEAL=self.palette['primary'];CORAL=self.palette['secondary'];GOLD=self.palette['accent']
        def txt(s,p,role='label',color='ink'): return self.label(s,p,color,role)
        def bead(p):return Circle(radius=.15,fill_color=TEAL,fill_opacity=.85,stroke_color=INK,stroke_width=1.5).move_to(p)
        beads=VGroup(*[bead([-2.45+.7*i,2.9,0]) for i in range(8)])
        self.add(beads)
        self.at('These two');self.play(beads.animate.shift(DOWN*.2),run_time=.8)
        self.at('Group these');pos3=[[-2.1+(i%3)*.5,3.0-(i//3)*.75,0] if i<6 else [1.6+(i-6)*.6,2.6,0] for i in range(8)];self.play(*[b.animate.move_to(p) for b,p in zip(beads,pos3)],run_time=1.2)
        groups3=VGroup(*[RoundedRectangle(width=1.55,height=.5,corner_radius=.14,stroke_color=INK,stroke_width=2).move_to([-1.6,3-j*.75,0]) for j in range(2)])
        self.play(Create(groups3),run_time=.5);rem=txt('divide by 3 · remainder 2',[0,.9,0],'claim');self.play(FadeIn(rem),run_time=.4)
        self.at('Regroup the same');self.play(FadeOut(groups3),FadeOut(rem),run_time=.3);pos5=[[-2.35+(i%3)*.5,3.1-(i//3)*.5,0] if i<5 else [1.0+(i-5)*.55,2.7,0] for i in range(8)];self.play(*[b.animate.move_to(p) for b,p in zip(beads,pos5)],run_time=1.2)
        group5=RoundedRectangle(width=1.65,height=1.05,corner_radius=.16,stroke_color=INK,stroke_width=2).move_to([-1.85,2.85,0]);self.play(Create(group5),run_time=.4);rem=txt('divide by 5 · remainder 3',[0,.9,0],'claim');self.play(FadeIn(rem),run_time=.4)
        self.at('Suppose you forget');self.play(FadeOut(VGroup(beads,group5)),run_time=.5);clues=txt('÷3 → remainder 2\n÷5 → remainder 3',[0,4.5,0],'claim');self.play(FadeIn(clues),FadeOut(rem),run_time=.5)
        self.at('Which counts');counts=VGroup(*[txt(str(n),[-2.4+(n%5)*1.2,2.6-(n//5)*1.05,0]) for n in range(15)]);self.play(FadeIn(counts),run_time=.6)
        self.at('Among zero');selected=VGroup(*[SurroundingRectangle(counts[n],buff=.18,color=TEAL,stroke_width=3) for n in range(15) if n%3==2]);self.play(LaggedStart(*[Create(x) for x in selected],lag_ratio=.3),run_time=1.4)
        self.at('Only eight');chosen=SurroundingRectangle(counts[8],buff=.26,color=CORAL,stroke_width=4);self.play(Create(chosen),run_time=.6)
        self.at('This table');self.play(FadeOut(VGroup(clues,selected,chosen)),run_time=.4)
        def cell(n):return np.array([-2.4+(n%5)*1.2,2.6-(n%3)*1.05,0])
        grid=VGroup(*[Rectangle(width=1.14,height=.99,stroke_color=INK,stroke_width=1.2).move_to([-2.4+c*1.2,2.6-r*1.05,0]) for r in range(3) for c in range(5)])
        heading=txt('remainders after division',[0,5,0],'claim');col=VGroup(*[txt(str(c),[-2.4+c*1.2,3.55,0]) for c in range(5)]);row=VGroup(*[txt(str(r),[-3.3,2.6-r*1.05,0]) for r in range(3)]);axislabels=VGroup(txt('by 5',[0,4.2,0]),txt('by 3',[-2.6,-1.3,0]));self.play(*[counts[n].animate.move_to(cell(n)) for n in range(15)],run_time=1.3);self.play(Create(grid),FadeIn(VGroup(heading,col,row,axislabels)),run_time=.6)
        self.at('The row tells')
        self.at('Follow eight');chosen=Rectangle(width=1.14,height=.99,stroke_color=CORAL,stroke_width=4).move_to(cell(8));self.play(Create(chosen),Indicate(row[2],color=CORAL),Indicate(col[3],color=CORAL),run_time=1)
        self.at('Every cell');self.at('Why does');self.play(FadeOut(VGroup(counts,grid,heading,col,row,axislabels,chosen)),run_time=.6)
        extra=VGroup(*[bead([-2+(i%5)*.75,3.6-(i//5)*.75,0]) for i in range(15)]);label=txt('add 15',[0,5,0],'claim');self.play(FadeIn(extra),FadeIn(label),run_time=.6)
        self.at('Adding fifteen');threes=VGroup(*[RoundedRectangle(width=.5,height=2.05,corner_radius=.12,stroke_color=INK,stroke_width=2).move_to([-2+c*.75,2.85,0]) for c in range(5)]);self.play(Create(threes),run_time=.8);eq=txt('5 complete groups of 3',[0,.8,0],'claim');self.play(FadeIn(eq),run_time=.4);self.wait(.7);fives=VGroup(*[RoundedRectangle(width=3.55,height=.5,corner_radius=.12,stroke_color=INK,stroke_width=2).move_to([-.5,3.6-r*.75,0]) for r in range(3)]);self.play(FadeOut(threes),Create(fives),run_time=.8);eq=self.replace_label(eq,txt('3 complete groups of 5',[0,.8,0],'claim'))
        self.at('Neither remainder');fixed=txt('same remainders: 2 and 3',[0,-1,0],'claim');self.play(FadeIn(fixed),run_time=.4)
        self.at('So eight');family=txt('8 → 23 → 38',[0,-2.5,0],'claim');self.play(FadeIn(family),run_time=.6)
        self.at('Conversely two');self.play(FadeOut(VGroup(extra,label,fives,eq,fixed,family)),run_time=.6);proof=VGroup(txt('same remainders',[0,4.5,0],'claim'),txt('difference = multiple of 3',[0,2.9,0]),txt('difference = multiple of 5',[0,1.9,0]));self.play(FadeIn(proof),run_time=.5)
        self.at('Because three');conclusion=txt('difference = multiple of 15',[0,.3,0],'claim');self.play(FadeIn(conclusion),run_time=.6)
        self.at('The clues identify');blocks=VGroup(*[VGroup(Rectangle(width=1.9,height=1.05,stroke_color=INK,stroke_width=1.5),txt(str(8+15*j),[0,0,0],'claim','secondary'),txt(f'{15*j}–{15*j+14}',[0,-.95,0])).move_to([-2.25+j*2.25,-2.3,0]) for j in range(3)]);self.play(FadeIn(blocks),run_time=.7)
        self.at('This is a small');self.play(FadeOut(VGroup(proof,conclusion)),run_time=.5);title=txt('Chinese remainder theorem',[0,3.8,0],'claim');rule=txt('x = 8 + 15k',[0,2.2,0],'claim');integer=txt('counts: k = 0, 1, 2, …',[0,1.25,0]);self.play(FadeIn(VGroup(title,rule,integer)),run_time=.6)
        self.at('Coprime divisors');self.at('Without a known');self.finish()
