from scenes._shared.design import *
class Film(Stage):
    def construct(self):
        r=ValueTracker(1);o=np.array([-2.5,3.1,0])
        lantern=VGroup(RoundedRectangle(width=.65,height=.85,corner_radius=.12,stroke_color=self.palette['ink'],fill_color=self.palette['accent'],fill_opacity=.3).move_to(o),Arc(radius=.22,start_angle=0,angle=PI,color=self.palette['ink']).move_to(o+[0,.56,0]),Line(o+[-.38,-.5,0],o+[.38,-.5,0],color=self.palette['ink']),Dot(o,radius=.09,color=self.palette['accent']))
        self.add(lantern)
        def x():return -2.5+1.6*r.get_value()
        screen=always_redraw(lambda:self.line([x(),3.1-.3*r.get_value(),0],[x(),3.1+.3*r.get_value(),0],'primary',8))
        rays=always_redraw(lambda:VGroup(*[self.line(o,[x(),3.1+s*.3*r.get_value(),0],'accent',2) for s in [-1,1]]))
        distance=always_redraw(lambda:self.label(f'distance {r.get_value():.0f}',[0,1.55,0],'muted','label'))
        self.add(rays,screen,distance);self.at('Step away');self.play(r.animate.set_value(2),run_time=3)
        self.at('The lantern has');self.focus_outline(lantern,run_time=.6)
        self.at('The same outgoing');self.play(r.animate.set_value(1),run_time=2)
        self.at('Imagine a tiny');assume=self.label('tiny source • clear space',[0,5.05,0],'muted','label').scale(.85);self.play(FadeIn(assume),run_time=.4)
        self.at('Follow one small');view=self.label('front view of the light bundle',[0,1.1,0],'ink','label').scale(.85);self.play(FadeIn(view),run_time=.5)
        face=always_redraw(lambda:Square(side_length=.9*r.get_value(),stroke_color=self.palette['primary'],fill_color=self.palette['accent'],fill_opacity=.65/r.get_value()**2).move_to([0,-.65,0]));self.add(face)
        self.at('Twice as far');self.play(r.animate.set_value(2),run_time=2.5)
        self.at('That makes four');grid=VGroup(self.line([-.9,-.65,0],[.9,-.65,0],'primary',2),self.line([0,-1.55,0],[0,.25,0],'primary',2));self.play(Create(grid),run_time=.6)
        self.at('The same energy');arrows=VGroup(*[self.label('¼',[a,b,0],'ink','label') for a in [-.45,.45] for b in [-1.1,-.2]]);self.play(FadeIn(arrows),run_time=.7)
        self.at('Each patch');self.focus_outline(face,run_time=.6)
        self.at('This is the inverse');rule=self.label('light per area ∝ 1 / distance²',[0,-2.65,0],'ink','label').scale(.85);self.play(FadeIn(rule),run_time=.6)
        self.at('Distance is squared');self.wait(.2)
        self.at('A real lantern');self.play(FadeOut(rule),run_time=.4)
        self.at('The tiny-source');self.focus_outline(assume,run_time=.6)
        self.at('The shaded');legend=self.label('shading encodes energy',[0,-2.65,0],'muted','label');self.play(FadeIn(legend),run_time=.5)
        self.at('Move the screen');self.play(FadeOut(grid),FadeOut(arrows),r.animate.set_value(3),run_time=2.4)
        self.at('The bundle now');grid3=VGroup(*[self.line([-1.35,y,0],[1.35,y,0],'primary',2) for y in [-1.1,-.2]],*[self.line([x,-2,0],[x,.7,0],'primary',2) for x in [-.45,.45]]);self.play(Create(grid3),run_time=.6)
        self.at('Each receives');ninth=self.label('⅑ per patch',[0,-3.35,0],'ink','claim');self.play(FadeIn(ninth),run_time=.5)
        self.at('Bring the screen');self.play(FadeOut(grid3),FadeOut(ninth),r.animate.set_value(1),run_time=2.5);self.finish()
