from scenes._shared.design import *
class Film(Stage):
    def construct(self):
        y=.2;xb=-2.7;h=3;xs=-2.7;hs=.6;ratio=ValueTracker(1.5)
        # Two aligned side-view panels share the sunlight angle, not a false perspective scale.
        base=np.array([xb,y,0]);smallbase=np.array([xs,-2.7,0])
        trunk=Line(base,base+[0,h,0],color=self.palette['ink'],stroke_width=8)
        leaves=VGroup(*[Ellipse(width=1.05,height=.52,fill_color=self.palette['primary'],fill_opacity=.24,stroke_color=self.palette['primary'],stroke_width=1).rotate(a).move_to(base+[dx,dy,0]) for dx,dy,a in [(-.35,2.45,.5),(.35,2.65,-.5),(0,2.95,1.2)]])
        leaves.stretch_to_fit_height(1.2).move_to(base+[0,h-.6,0])
        stick=Line(smallbase,smallbase+[0,hs,0],stroke_color=self.palette['ink'],stroke_width=5)
        ground=VGroup(self.line([-3.2,y,0],[3.2,y,0],'muted',2),self.line([-3.2,-2.7,0],[3.2,-2.7,0],'muted',2))
        shadow=always_redraw(lambda:Line(base,base+[h*ratio.get_value(),0,0],color=self.palette['secondary'],stroke_width=10))
        short=always_redraw(lambda:Line(smallbase,smallbase+[hs*ratio.get_value(),0,0],color=self.palette['secondary'],stroke_width=7))
        ray=always_redraw(lambda:self.line(base+[0,h,0],base+[h*ratio.get_value(),0,0],'accent',3))
        sray=always_redraw(lambda:self.line(smallbase+[0,hs,0],smallbase+[hs*ratio.get_value(),0,0],'accent',3))
        self.add(ground,trunk,leaves,shadow,stick,short);self.at('A tree can');self.wait(.3)
        self.at('Its shadow carries');self.play(ratio.animate.set_value(1.8),run_time=1.8)
        self.at('A little upright');self.focus_outline(stick,run_time=.7)
        self.at('For this moment');self.play(FadeIn(ray),FadeIn(sray),run_time=.7)
        self.at('The ground is level');self.wait(.2)
        self.at('The tree, its');self.play(leaves.animate.set_opacity(.18),run_time=.5);big=always_redraw(lambda:self.poly(base,base+[0,h,0],base+[h*ratio.get_value(),0,0],color='primary',opacity=.08));self.add(big)
        self.at('The stick makes');small=self.poly(smallbase,smallbase+[0,hs,0],smallbase+[hs*ratio.get_value(),0,0],color='secondary',opacity=.22);self.play(FadeIn(small),run_time=.6)
        self.at('Enlarge the small');copy=small.copy();self.add(copy);self.play(copy.animate.scale(5,about_point=smallbase).shift(base-smallbase),run_time=2.2)
        self.at('Its height must');self.focus_outline(trunk,run_time=.6)
        self.at('This is what');label=self.label('same scale for height and shadow',[0,-.8,0],'ink','label');label.scale(.75);self.play(FadeIn(label),run_time=.5)
        self.at('Suppose a one');self.play(FadeOut(copy),FadeOut(small),FadeOut(label),run_time=.4);self.play(ratio.animate.set_value(2),run_time=.6);smalllabels=VGroup(self.label('1 m',[-3.2,-2.35,0],'ink','label'),self.label('2 m',[-2.1,-3.3,0],'secondary','label'));self.play(FadeIn(smalllabels),run_time=.4)
        self.at('A ten-metre');ten=self.label('10 m',[.3,-.3,0],'secondary','label');self.play(FadeIn(ten),run_time=.4)
        self.at('The tree is therefore');five=self.label('5 m',[-3.4,1.8,0],'ink','claim');self.play(FadeIn(five),run_time=.5)
        self.at('We used a comparison');rule=self.label('10 ÷ 2 = 5 ÷ 1',[0,-1.15,0],'ink','label');self.play(FadeIn(rule),run_time=.4)
        self.at('As the sun rises');self.play(FadeOut(ten),FadeOut(smalllabels),FadeOut(rule),run_time=.4);self.play(ratio.animate.set_value(1),run_time=2)
        self.at('The ratio between the two heights');invariant=self.label('height ratio = shadow ratio',[0,-1.1,0],'ink','label');invariant.scale(.8);self.play(FadeIn(invariant),run_time=.4)
        self.at('Measure them');self.play(leaves.animate.set_opacity(1),run_time=.6)
        self.at('Something difficult');self.finish()
