from scenes._shared.design import *
class Film(Stage):
    def construct(self):
        def coin(i,pos,col='accent'):return VGroup(Circle(radius=.34,fill_color=self.palette[col],fill_opacity=1,stroke_color=self.palette['ink'],stroke_width=2),self.label(str(i),ORIGIN,'ink','detail')).move_to(pos)
        coins=VGroup(*[coin(i+1,[(i%3-1)*1.6,3-(i//3)*1.3,0]) for i in range(9)]);self.add(coins);self.play(LaggedStart(*[c.animate.shift(DOWN*.12) for c in coins],lag_ratio=.12),run_time=.8);self.say('9 coins. Only 2 weighings.')
        self.at('Left heavy');self.say('Left • right • balanced')
        self.at('Make three groups');targets=[[(-2.1+g*2.1)+(j-1)*.52,2.4,0] for g in range(3) for j in range(3)];self.play(*[c.animate.scale(.72).move_to(pos) for c,pos in zip(coins,targets)],run_time=1)
        pivot=np.array([0,-.5,0]);beam=self.line([-2,-.5,0],[2,-.5,0],'ink',6);stand=VGroup(self.poly([-.4,-2,0],[.4,-2,0],[0,-.5,0],color='surface',opacity=1),self.line([-1,-2,0],[1,-2,0],'ink',6));left=self.line([-2.6,-1.0,0],[-1.0,-1.0,0],'primary',5);right=self.line([1,-1,0],[2.6,-1,0],'primary',5);self.add(stand,beam,left,right);hangers=always_redraw(lambda:VGroup(self.line(beam.get_start(),left.get_center(),'muted',2),self.line(beam.get_end(),right.get_center(),'muted',2)));self.add(hangers)
        self.at('Weigh the first group');self.play(*[coins[i].animate.move_to([-1.8+(i-1)*.5,-.68,0]) for i in range(3)],*[coins[i].animate.move_to([1.8+(i-4)*.5,-.68,0]) for i in range(3,6)],run_time=1)
        self.at('If the left side drops');self.play(Rotate(beam,.12,about_point=pivot),left.animate.shift(DOWN*.24),right.animate.shift(UP*.24),coins[:3].animate.shift(DOWN*.24),coins[3:6].animate.shift(UP*.24),run_time=.7)
        self.at('If the right side drops');self.play(Rotate(beam,-.24,about_point=pivot),left.animate.shift(UP*.48),right.animate.shift(DOWN*.48),coins[:3].animate.shift(UP*.48),coins[3:6].animate.shift(DOWN*.48),run_time=.7)
        self.at('If they balance, the heavy coin must');self.play(Rotate(beam,.12,about_point=pivot),left.animate.shift(DOWN*.24),right.animate.shift(UP*.24),coins[:3].animate.shift(DOWN*.24),coins[3:6].animate.shift(UP*.24),run_time=.7);self.play(Indicate(coins[6:]),run_time=.7)
        self.at('Every answer leaves');self.wait(.2)
        self.at('Let us take');self.play(FadeOut(coins[:6]),run_time=.5);self.say('Balanced → keep 7, 8, 9')
        self.at('Now weigh seven');self.play(coins[6].animate.scale(1.8).move_to([-1.8,-.54,0]),coins[7].animate.scale(1.8).move_to([1.8,-.54,0]),coins[8].animate.scale(1.8).move_to([0,2.4,0]),run_time=1)
        self.at('If seven drops');self.play(Indicate(coins[6]),run_time=.6)
        self.at('If eight drops');self.play(Indicate(coins[7]),run_time=.6)
        self.at('untouched ninth coin');self.play(Indicate(coins[8]),run_time=.6)
        self.at('Here, eight drops');self.play(Rotate(beam,-.12,about_point=pivot),left.animate.shift(UP*.24),right.animate.shift(DOWN*.24),coins[6].animate.shift(UP*.24),coins[7].animate.shift(DOWN*.24),run_time=.7);self.say('Coin 8. Two weighings.')
        self.at('Two weighings, one answer');self.wait(.2)
        self.at('Three outcomes, followed');self.play(*[FadeOut(m) for m in list(self.mobjects) if m is not self.caption],run_time=.5);self.add(self.label('3 × 3 = 9',[0,1.5,0],'primary','claim'));self.say('Balance is an answer too.')
        self.at('might be lighter');self.say('Known heavier is essential.',color='secondary')
        self.at('What about twenty seven');self.say('27 coins: how many weighings?')
        self.at('So three weighings');self.add(self.label('3 × 3 × 3 = 27',[0,-.4,0],'primary','claim'));self.finish()
