from scenes._shared.design import *
class Film(Stage):
    def construct(self):
        left=np.array([-2.5,1.3,0]);right=np.array([2.5,1.3,0]);road=self.line(left,right,'muted',3)
        home=VGroup(self.poly([-2.9,2,0],[-2.9,2.7,0],[-2.1,2.7,0],[-2.1,2,0],color='accent',opacity=.2),self.poly([-3,2.7,0],[-2.5,3.2,0],[-2,2.7,0],color='secondary',opacity=.25))
        pond=Ellipse(width=1.5,height=.65,color=self.palette['primary'],fill_color=self.palette['primary'],fill_opacity=.3).move_to([2.4,2.3,0])
        walker=VGroup(Circle(radius=.13,color=self.palette['ink']).shift(UP*.55),Line([0,.4,0],[0,0,0],color=self.palette['ink']),Line([0,0,0],[-.18,-.3,0],color=self.palette['ink']),Line([0,0,0],[.18,-.3,0],color=self.palette['ink']),Line([-.23,.14,0],[.23,.3,0],color=self.palette['ink'])).move_to(left+UP*.5)
        self.add(home,pond,road,walker);self.at('A walk to');self.wait(.2)
        self.at('You stroll out');self.play(walker.animate.move_to(right+UP*.5),run_time=2.4,rate_func=linear);self.play(walker.animate.move_to(left+UP*.5),run_time=1.2,rate_func=linear)
        self.at('The faster half');self.wait(.3)
        self.at('Let the pond');distance=self.label('3 km',[0,.8,0],'ink','label');self.play(FadeIn(distance),run_time=.4)
        self.at('At three kilometres');speed=self.label('3 km/h → 1 hour',[0,-.1,0],'primary','claim');self.play(FadeIn(speed),walker.animate.move_to(right+UP*.5),run_time=3,rate_func=linear)
        self.at('At six kilometres');self.play(FadeOut(speed),run_time=.25);speed=self.label('6 km/h → ½ hour',[0,-.1,0],'secondary','claim');self.play(FadeIn(speed),walker.animate.move_to(left+UP*.5),run_time=1.5,rate_func=linear)
        self.at('The slow part');self.wait(.3)
        self.at('Lay those times');self.play(FadeOut(speed),run_time=.4);a=Rectangle(width=3,height=.65,stroke_width=0,fill_color=self.palette['primary'],fill_opacity=.5).move_to([-.75,-.6,0]);b=Rectangle(width=1.5,height=.65,stroke_width=0,fill_color=self.palette['secondary'],fill_opacity=.5).move_to([1.5,-.6,0]);self.play(FadeIn(a),FadeIn(b),run_time=.7);labels=VGroup(self.label('1 hour',[-.75,-1.3,0],'primary','label'),self.label('½ hour',[1.5,-1.3,0],'secondary','label'));self.add(labels)
        self.at('Six kilometres have taken');sumtime=self.label('6 km ÷ 1.5 h',[0,-2.1,0],'ink','claim');self.play(FadeIn(sumtime),run_time=.4)
        self.at('The average speed');answer=self.label('4 km/h',[0,-2.95,0],'ink','claim');self.play(FadeIn(answer),run_time=.5)
        self.at('The simple average');self.wait(.2)
        self.at('That would weight');self.focus_outline(a,run_time=.6)
        self.at('For equal distances');self.play(FadeOut(sumtime),FadeOut(answer),run_time=.5);eq=self.label('time = distance ÷ speed',[0,-2.1,0],'ink','label');self.play(FadeIn(eq),run_time=.4)
        self.at('Add the two');self.play(FadeOut(eq),run_time=.3);eq=self.label('average = 2 ÷ (1/u + 1/v)',[0,-2.1,0],'ink','label');eq.scale(.88);self.play(FadeIn(eq),run_time=.4)
        self.at('This gives');name=self.label('harmonic mean',[0,-2.95,0],'primary','label');self.play(FadeIn(name),run_time=.4)
        self.at('Its shape');self.wait(.2)
        self.at('If you spent equal');self.play(FadeOut(eq),FadeOut(name),FadeOut(labels),run_time=.4);self.play(a.animate.stretch_to_fit_width(2.25).move_to([-1.125,-.6,0]),b.animate.stretch_to_fit_width(2.25).move_to([1.125,-.6,0]),run_time=1);equal=self.label('equal time → (3 + 6) ÷ 2 = 4.5',[0,-1.6,0],'ink','label');equal.scale(.78);self.play(FadeIn(equal),run_time=.4)
        self.at('The important question');self.wait(.2)
        self.at('Distance, or time');self.focus_outline(VGroup(a,b),run_time=.7)
        self.at('A small change');self.finish()
