from scenes._shared.design import *
class Film(Stage):
    def construct(self):
        y=2.3;depth=2.5;n=4/3;theta=12*DEGREES;xa=depth*math.tan(theta);air=math.asin(n*math.sin(theta));apparent=xa/math.tan(air)
        water=Rectangle(width=6,height=3.3,stroke_width=0,fill_color=self.palette['primary'],fill_opacity=.12).move_to([0,y-1.65,0]);surface=self.line([-3,y,0],[3,y,0],'primary',3);bowl=VMobject(stroke_color=self.palette['ink'],stroke_width=3).set_points_as_corners([[-3,y+.3,0],[-3,y-3.3,0],[3,y-3.3,0],[3,y+.3,0]])
        def coin(yy,opacity=1):return VGroup(Ellipse(width=.65,height=.22,fill_color=self.palette['accent'],fill_opacity=.7*opacity,stroke_color=self.palette['ink'],stroke_opacity=opacity),Ellipse(width=.44,height=.1,stroke_color=self.palette['ink'],stroke_opacity=opacity)).move_to([0,yy,0])
        real=coin(y-depth,.28);virtual=coin(y-apparent);self.add(water,surface,bowl,real,virtual)
        self.at('A coin under water');self.wait(.2)
        self.at('The coin has stayed');self.play(real.animate.set_opacity(1),run_time=.6)
        self.at('The light bringing');self.wait(.3)
        under=VGroup();above=VGroup();back=VGroup();normals=VGroup()
        for sign in [-1,1]:
         p=np.array([sign*xa,y,0]);q=p+np.array([sign*math.tan(air)*1.5,1.5,0]);under.add(self.line([0,y-depth,0],p,'accent',4));above.add(self.line(p,q,'accent',4));back.add(DashedLine(p,[0,y-apparent,0],color=self.palette['secondary'],stroke_width=3));normals.add(DashedLine(p+[0,-.5,0],p+[0,.7,0],color=self.palette['muted'],stroke_width=1))
        self.at('Follow two rays');self.play(virtual.animate.set_opacity(.3),Create(under),run_time=1.4)
        self.at('As light leaves');self.play(Create(above),Create(normals),run_time=1.2)
        self.at('Your eye traces');self.play(Create(back),run_time=1.5)
        self.at('Those backward lines');self.play(virtual.animate.set_opacity(1),run_time=.6);self.focus_outline(virtual,run_time=.6)
        self.at('That meeting point');tag=self.label('virtual image',[1.75,y-apparent,0],'secondary','label');tag.scale(.8);self.play(FadeIn(tag),run_time=.4)
        self.at('Light does not actually');self.wait(.2)
        self.at('It only arrives');self.focus_outline(back,run_time=.7)
        self.at('The change happens');self.focus_outline(surface,run_time=.7)
        self.at('Looking nearly');self.play(FadeOut(normals),FadeOut(tag),run_time=.4)
        actual=DoubleArrow([-2,y-depth,0],[-2,y,0],buff=0,color=self.palette['ink'],stroke_width=3);imageheight=DoubleArrow([2,y-apparent,0],[2,y,0],buff=0,color=self.palette['secondary'],stroke_width=3);self.play(Create(actual),Create(imageheight),run_time=.8)
        rule=self.label('apparent depth ≈ ¾ × real depth',[0,-2,0],'ink','label');rule.scale(.78);self.play(FadeIn(rule),run_time=.5)
        self.at('Water has');index=self.label('water ≈ 4/3    air ≈ 1',[0,-2.85,0],'muted','label');self.play(FadeIn(index),run_time=.4)
        self.at('The near-vertical');self.wait(.3)
        self.at('A coin four');numbers=VGroup(self.label('4',[-2.5,.9,0],'ink','label'),self.label('≈ 3',[2.5,1.4,0],'secondary','label'));self.play(FadeIn(numbers),run_time=.4)
        self.at('This simple depth');self.play(FadeOut(index),run_time=.3);note=self.label('small-angle approximation',[0,-2.85,0],'muted','label');note.scale(.85);self.play(FadeIn(note),run_time=.4)
        self.at('At wider angles');self.wait(.2)
        self.at('A familiar object');self.finish()
